#!/bin/bash
REPO_PATH=$(git rev-parse —show-toplevel)
check_substring() {
local substring="HELP_ME"
local files=$(git diff —cached —name-only)
for file in $files; do
if grep -q "$substring" "$REPO_PATH/$file"; then
echo "Ошибка: обнаружена подстрока '$substring' в файле $file"
exit 1
fi
done
}

check_substring
exit 0 
